[package]
name = "uxfd-shared-video-frame-bridge-node"
version = "0.1.0-Alpha-1a"
edition = "2021"
build = "build.rs"

[lib]
name = "uxfd_shared_video_frame_bridge_node"
crate-type = ["cdylib"]

[dependencies]
napi = "3.9.2"
napi-derive = "3.5.6"
uxfd-shared-video-frame-bridge = { path = "../shared-video-frame-bridge" }

[build-dependencies]
napi-build = "2.3.2"
