import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const source = () =>
  readFileSync(new URL('./TimelineContextMenu.tsx', import.meta.url), 'utf8');

describe('TimelineContextMenu particle insertion boundary', () => {
  it('exposes the AviUtlPackV4 standard particle insertion command', () => {
    const code = source();

    expect(code).toContain('buildAviUtlHoundstoothObject');
    expect(code).toContain('buildAviUtlYagasuriObject');
    expect(code).toContain('buildAviUtlPaperAirplaneObject');
    expect(code).toContain('buildAviUtlAsanohaPatternObject');
    expect(code).toContain('buildAviUtlAudioSphereObject');
    expect(code).toContain('buildAviUtlFocusLinesPlusObject');
    expect(code).toContain('buildAviUtlRandomLineExObject');
    expect(code).toContain('buildAviUtlHologramObject');
    expect(code).toContain('buildAviUtlProtractorObject');
    expect(code).toContain('buildAviUtlShakingPolygonObject');
    expect(code).toContain('buildAviUtlCircularArrowObject');
    expect(code).toContain('buildAviUtlTartanCheckObject');
    expect(code).toContain('buildAviUtlTriangleBracketObject');
    expect(code).toContain('buildAviUtlBarcodeObject');
    expect(code).toContain('buildAviUtlColourWheelObject');
    expect(code).toContain('buildAviUtlGearObject');
    expect(code).toContain('buildAviUtlGourdObject');
    expect(code).toContain('buildAviUtlHistogramObject');
    expect(code).toContain('buildGetColorDotFieldObject');
    expect(code).toContain('buildHksyCheckerGridObject');
    expect(code).toContain('buildHksyDiamondObject');
    expect(code).toContain('buildHksyLineObject');
    expect(code).toContain('buildHksyMeasuredGridObject');
    expect(code).toContain('buildHksyMultiColourCheckerObject');
    expect(code).toContain('buildAviUtlToneCurveObject');
    expect(code).toContain('buildAviUtlPuzzlePieceObject');
    expect(code).toContain('buildAviUtlAuraEmissionObject');
    expect(code).toContain('buildAviUtlBubbleObject');
    expect(code).toContain('buildAviUtlFocusLinesObject');
    expect(code).toContain('buildAviUtlInkSplashObject');
    expect(code).toContain('buildAviUtlPieChartObject');
    expect(code).toContain('buildAviUtlSunburstObject');
    expect(code).toContain('buildAviUtlTrackBarObject');
    expect(code).toContain('buildDefaultStandardParticleObject');
    expect(code).toContain('handleAddHoundstooth');
    expect(code).toContain('handleAddYagasuri');
    expect(code).toContain('handleAddPaperAirplane');
    expect(code).toContain('handleAddAsanohaPattern');
    expect(code).toContain('handleAddAudioSphere');
    expect(code).toContain('handleAddFocusLinesPlus');
    expect(code).toContain('handleAddRandomLineEx');
    expect(code).toContain('handleAddHologram');
    expect(code).toContain('handleAddProtractor');
    expect(code).toContain('handleAddShakingPolygon');
    expect(code).toContain('handleAddCircularArrow');
    expect(code).toContain('handleAddTartanCheck');
    expect(code).toContain('handleAddTriangleBracket');
    expect(code).toContain('handleAddBarcode');
    expect(code).toContain('handleAddColourWheel');
    expect(code).toContain('handleAddGear');
    expect(code).toContain('handleAddGourd');
    expect(code).toContain('handleAddHistogram');
    expect(code).toContain('handleAddGetColorDotField');
    expect(code).toContain('handleAddHksyCheckerGrid');
    expect(code).toContain('handleAddHksyDiamond');
    expect(code).toContain('handleAddHksyLine');
    expect(code).toContain('handleAddHksyMeasuredGrid');
    expect(code).toContain('handleAddHksyMultiColourChecker');
    expect(code).toContain('handleAddToneCurve');
    expect(code).toContain('handleAddPuzzlePiece');
    expect(code).toContain('handleAddParticle');
    expect(code).toContain('handleAddAuraEmission');
    expect(code).toContain('handleAddBubble');
    expect(code).toContain('handleAddFocusLines');
    expect(code).toContain('handleAddInkSplash');
    expect(code).toContain('handleAddPieChart');
    expect(code).toContain('handleAddSunburst');
    expect(code).toContain('handleAddTrackBar');
    expect(code).toContain('Add Houndstooth');
    expect(code).toContain('Add Yagasuri');
    expect(code).toContain('Add Paper Airplane');
    expect(code).toContain('Add Asanoha Pattern');
    expect(code).toContain('Add 93 Audio Sphere');
    expect(code).toContain('Add Focus Lines Plus');
    expect(code).toContain('Add Random Line EX');
    expect(code).toContain('Add Hologram');
    expect(code).toContain('Add Protractor');
    expect(code).toContain('Add Shaking Polygon');
    expect(code).toContain('Add Barcode');
    expect(code).toContain('Add Circular Arrow');
    expect(code).toContain('Add Tartan Check');
    expect(code).toContain('Add Triangle Bracket');
    expect(code).toContain('Add Colour Wheel');
    expect(code).toContain('Add Gear');
    expect(code).toContain('Add Gourd');
    expect(code).toContain('Add Histogram');
    expect(code).toContain('Add GetColor V2R Dot Field');
    expect(code).toContain('Add hksy Checker/Grid');
    expect(code).toContain('Add hksy Diamond');
    expect(code).toContain('Add hksy Lines');
    expect(code).toContain('Add hksy Grid');
    expect(code).toContain('Add hksy Multi-Colour Checker');
    expect(code).toContain('Add Tone Curve');
    expect(code).toContain('Add Puzzle Piece');
    expect(code).toContain('Add Standard Particle');
    expect(code).toContain('Add Aura Emission');
    expect(code).toContain('Add Bubbles');
    expect(code).toContain('Add Focus Lines');
    expect(code).toContain('Add Ink Splash');
    expect(code).toContain('Add Pie Chart');
    expect(code).toContain('Add Sunburst');
    expect(code).toContain('Add Track Bar');
    expect(code).toContain('千鳥格子を追加');
    expect(code).toContain('矢がすりを追加');
    expect(code).toContain('紙飛行機を追加');
    expect(code).toContain('麻の葉模様を追加');
    expect(code).toContain('93音声玉を追加');
    expect(code).toContain('集中線plusを追加');
    expect(code).toContain('ランダムラインEXを追加');
    expect(code).toContain('ホログラムを追加');
    expect(code).toContain('分度器を追加');
    expect(code).toContain('多角形_震えるを追加');
    expect(code).toContain('バーコードを追加');
    expect(code).toContain('円矢印を追加');
    expect(code).toContain('タータンチェックを追加');
    expect(code).toContain('三角括弧を追加');
    expect(code).toContain('色相環を追加');
    expect(code).toContain('歯車を追加');
    expect(code).toContain('ひょうたんを追加');
    expect(code).toContain('簡易ヒストグラムを追加');
    expect(code).toContain('GetColor V2Rドットフィールドを追加');
    expect(code).toContain('hksyチェッカー/グリッドを追加');
    expect(code).toContain('hksy菱形を追加');
    expect(code).toContain('hksy直線を追加');
    expect(code).toContain('hksyグリッドを追加');
    expect(code).toContain('hksy複数色チェッカーを追加');
    expect(code).toContain('簡易トーンカーブを追加');
    expect(code).toContain('パズルピースを追加');
    expect(code).toContain('標準パーティクルを追加');
    expect(code).toContain('オーラ放出を追加');
    expect(code).toContain('泡を追加');
    expect(code).toContain('集中線を追加');
    expect(code).toContain('インクを追加');
    expect(code).toContain('パイシートグラフを追加');
    expect(code).toContain('日の出を追加');
    expect(code).toContain('トラックバーを追加');
  });
});
